name: findoc-analyzer

services:
  postgres:
    image: postgres:18-alpine
    container_name: financial_db
    environment:
      POSTGRES_USER: danycb
      POSTGRES_PASSWORD: super_secret
      POSTGRES_DB: findoc_analyzer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    
volumes:
  postgres_data: