name: findoc-analyzer

services:
  postgres:
    image: pgvector/pgvector:0.8.2-pg18-trixie
    container_name: financial_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    restart: unless-stopped

volumes:
  pgdata: